routes/notification_gcpj_route.py
import time
from io import BytesIO

import pandas as pd
from app import db
from flask import Blueprint, render_template, send_file
from sqlalchemy import text


import plotly.graph_objs as go
from plotly.offline import plot

from permission_required import permission_required
from queries.notificacoes import import_notioficacoes_civel
import jwt


notification_gcpj_pb = Blueprint("notification_gcpj", __name__)

@notification_gcpj_pb.route("/dashboard")
@permission_required("todos")
def dashboard():
    vendas = [
        {"mes": "Janeiro", "quantidade": 10},
        {"mes": "Fevereiro", "quantidade": 15},
        {"mes": "Março", "quantidade": 13},
        {"mes": "Abril", "quantidade": 17}
    ]

    meses = [item["mes"] for item in vendas]
    quantidades = [item["quantidade"] for item in vendas]

    grafico = go.Bar(x=meses, y=quantidades)
    layout = go.Layout(title="Vendas por Mês", xaxis=dict(title="Mês"), yaxis=dict(title="Quantidade"))
    figura = go.Figure(data=[grafico], layout=layout)
    grafico_html = plot(figura, output_type="div", include_plotlyjs=True)

    ########
    METABASE_SITE_URL = "http://metabase.saratt.com.br"
    METABASE_SECRET_KEY = "cfda76a2c906ff51dd438dc5280c77876066db7f6412c92e0874d34cbf20f8f8"
    payload = {
        "resource": {"dashboard": 17},
        "params": {},
        "exp": round(time.time()) + 600
    }

    token = jwt.encode(payload, METABASE_SECRET_KEY, algorithm="HS256")
    iframe_url = f"{METABASE_SITE_URL}/embed/dashboard/{token}#bordered=true&titled=true"

    return render_template("dashboards/dashboard.html", grafico=grafico_html, iframe_url=iframe_url)

@notification_gcpj_pb.route("/tarefas-ti")
@permission_required("todos")
def tarefas_ti():
    ########
    METABASE_SITE_URL = "http://metabase.saratt.com.br"
    METABASE_SECRET_KEY = "cfda76a2c906ff51dd438dc5280c77876066db7f6412c92e0874d34cbf20f8f8"
    payload = {
        "resource": {"dashboard": 12},
        "params": {},
        "exp": round(time.time()) + 600
    }

    token = jwt.encode(payload, METABASE_SECRET_KEY, algorithm="HS256")
    iframe_url = f"{METABASE_SITE_URL}/embed/dashboard/{token}#background=false&bordered=false&titled=false"

    return render_template("dashboards/tarefas_ti.html", iframe_url=iframe_url)


@notification_gcpj_pb.route("/notificacoes")
@permission_required("todos")
def notificacoes():
    sql = text(import_notioficacoes_civel())
    resultado = db.session.execute(sql)

    pastas = [dict(row._mapping) for row in resultado]
    
    METABASE_SITE_URL = "http://metabase.saratt.com.br"
    METABASE_SECRET_KEY = "cfda76a2c906ff51dd438dc5280c77876066db7f6412c92e0874d34cbf20f8f8"
    payload = {
        "resource": {"dashboard": 17},
        "params": {},
        "exp": round(time.time()) + 600
    }

    token = jwt.encode(payload, METABASE_SECRET_KEY, algorithm="HS256")
    iframeUrl = METABASE_SITE_URL + "/embed/dashboard/" + token + "#theme=night&background=false&bordered=false&titled=false"

    return render_template("dashboards/notificacoes.html", pastas=pastas, iframe_url=iframeUrl)


@notification_gcpj_pb.route("/relatorio_ti")
@permission_required("todos")
def relatorio_ti():
    METABASE_SITE_URL = "http://metabase.saratt.com.br"
    METABASE_SECRET_KEY = "cfda76a2c906ff51dd438dc5280c77876066db7f6412c92e0874d34cbf20f8f8"

    payload = {
    "resource": {"dashboard": 12},
    "params": {
        
    },
    "exp": round(time.time()) + (60 * 10) # 10 minute expiration
    }
    token = jwt.encode(payload, METABASE_SECRET_KEY, algorithm="HS256")

    iframeUrl = METABASE_SITE_URL + "/embed/dashboard/" + token + "#background=false&bordered=false&titled=false"
    
    return render_template("dashboards/relatorio_ti.html", iframe_url=iframeUrl)  
    
    
    
@notification_gcpj_pb.route("/notificacoes/exportar")
@permission_required("todos")
def exportar_notificacoes_excel():
    sql = text(import_notioficacoes_civel())
    resultado = db.session.execute(sql)

    pastas = [dict(row._mapping) for row in resultado]

    if not pastas:
        return "Nenhuma notificação encontrada.", 404

    df = pd.DataFrame(pastas)

    output = BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name="Notificações")

    output.seek(0)
    return send_file(
        output,
        as_attachment=True,
        download_name="notificacoes_civeis.xlsx",
        mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    )

templates/dashboards/dashboard.html
{% extends 'base.html' %}
{% block conteudo %}
<div class="container">
    <h2 class="text-center mt-5">Dashboard com Gráfico</h2>
   
    
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-6">
                <div class="card-grafico">
                    {{ grafico | safe }}
                </div>
            </div>
            
            <div class="col-md-6">
                <div class="card-grafico">
                    <h5>Outro conteúdo aqui</h5>
                    <iframe src="{{ iframe_url }}" width="800" height="600" frameborder="0"></iframe>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock conteudo %}

templates/dashboards/notificacoes.html
{% extends 'base.html' %}
{% block conteudo %}

<br>
<iframe src="{{ iframe_url }}" class="iframe-full" frameborder="0"></iframe>

<div class="container">
    <div class="card-grafico">
        <iframe src="{{ iframe_url }}" class="iframe-full" frameborder="0"></iframe>
    </div>

</div>


<div class="container-fluid px-4">
    <h2 class="text-white mt-5">Dashboard com Gráfico</h2>

    <div class="row">
        <div class="col-12 col-xl-6 mb-4">
            <div class="card-grafico">
                <h5>Outro conteúdo aqui</h5>
                <p>Você pode colocar outro gráfico, texto ou componentes aqui.</p>
            </div>
        </div>
        <div class="col-12 col-xl-6 mb-4">
            <div class="card-grafico">
                <h5>Outro conteúdo aqui</h5>

                <iframe src="{{ iframe_url }}" width="800" height="600" frameborder="0"></iframe>
            </div>
        </div>

        <div class="col-12 col-xl-6 mb-4">
            <div class="card-grafico">
                <h2 class="text-dark mb-4">Notificações Cíveis</h2>
                {% if pastas %}
                <div class="table-responsive rounded-3 shadow">
                    <table class="table custom-table align-middle mb-0">
                        <thead>
                            <tr>
                                <th>Pasta ID</th>
                                <th>Data</th>
                                <th>Prazo Final</th>
                                <th>Responsável</th>
                                <th>Evento</th>
                                <th>Conteúdo</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for pasta in pastas %}
                            <tr>
                                <td>{{ pasta.pasta_id }}</td>
                                <td>{{ pasta.data }}</td>
                                <td>{{ pasta.prazo_final }}</td>
                                <td>{{ pasta.responsavel }}</td>
                                <td>{{ pasta.evento }}</td>
                                <td>{{ pasta.conteudo }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% else %}
                    <div class="alert alert-warning mt-4">Nenhuma notificação encontrada.</div>
                {% endif %}
                <br>
                <a href="{{ url_for('notification_gcpj.exportar_notificacoes_excel') }}" class="btn btn-success mt-3">Download Excel</a>
            </div>
            
        </div>
    </div>
</div>

{% endblock conteudo %}

templates/dashboards/relatorio_ti.html
{% extends 'base.html' %}
{% block conteudo %}

<iframe src="{{ iframe_url }}" class="iframe-full" frameborder="0"></iframe>

{% endblock conteudo %}

templates/dashboards/tarefas_ti.html
{% extends 'base.html' %}
{% block conteudo %}

<br>
<iframe src="{{ iframe_url }}" class="iframe-full" frameborder="0" width="100"></iframe>

{% endblock conteudo %}